from pathlib import Path

# Словарь с ключами имя корпуса. В значениях лежит словарь с ключами corpus, pairs, tree,ses, ud_rules_1, ud_rules_2, dict

config = {
    'SynTagRus':           {"corpus": Path("data/SynTagRus/corpus"),
                            "pairs": Path("data/SynTagRus/pairs_SynTagRus_corpus_not_unique.pkl"),
                            "trees": Path("data/SynTagRus/tree_set_SynTagRus_corpus.pkl"),
                            "ses": Path("data/SynTagRus/ses_set_SynTagRus_corpus.pkl"),
                            "ud_with_copy": Path("data/SynTagRus/ud_with_copy_set_SynTagRus_corpus.pkl"),
                            "ud_without_copy": Path("data/SynTagRus/ud_without_copy_set_SynTagRus_corpus.pkl"),
                            "dict_tree": Path("data/SynTagRus/syntagrus_f_x_dict_tree.pkl"),
                            "dict_ses": Path("data/SynTagRus/syntagrus_f_x_dict_ses.pkl"),
                            "dict_ud_with_copy": Path("data/SynTagRus/syntagrus_f_x_dict_ud_with_copy.pkl"),
                            "dict_ud_without_copy": Path("data/SynTagRus/syntagrus_f_x_dict_ud_without_copy.pkl")},
    'poetry':              {"corpus": Path("data/poetry/corpus"),
                            "pairs": Path("data/poetry/pairs_poetry_corpus_not_unique.pkl"),
                            "trees": Path("data/poetry/tree_set_poetry_corpus.pkl"),
                            "ses": Path("data/poetry/ses_set_poetry_corpus.pkl"),
                            "ud_with_copy": Path("data/poetry/ud_with_copy_set_poetry_corpus.pkl"),
                            "ud_without_copy": Path("data/poetry/ud_without_copy_set_poetry_corpus.pkl"),
                            "dict_tree": Path("data/poetry/poetry_f_x_dict_tree.pkl"),
                            "dict_ses": Path("data/poetry/poetry_f_x_dict_ses.pkl"),
                            "dict_ud_with_copy": Path("data/poetry/poetry_f_x_dict_ud_with_copy.pkl"),
                            "dict_ud_without_copy": Path("data/poetry/poetry_f_x_dict_ud_without_copy.pkl")},
    'taiga':               {"corpus": Path("data/taiga/corpus"),
                            "pairs": Path("data/taiga/pairs_taiga_corpus_not_unique.pkl"),
                            "trees": Path("data/taiga/tree_set_taiga_corpus.pkl"),
                            "ses": Path("data/taiga/ses_set_taiga_corpus.pkl"),
                            "ud_with_copy": Path("data/taiga/ud_with_copy_set_taiga_corpus.pkl"),
                            "ud_without_copy": Path("data/taiga/ud_without_copy_set_taiga_corpus.pkl"),
                            "dict_tree": Path("data/taiga/taiga_f_x_dict_tree.pkl"),
                            "dict_ses": Path("data/taiga/taiga_f_x_dict_ses.pkl"),
                            "dict_ud_with_copy": Path("data/taiga/taiga_f_x_dict_ud_with_copy.pkl"),
                            "dict_ud_without_copy": Path("data/taiga/taiga_f_x_dict_ud_without_copy.pkl")},
    'gsd':                 {"corpus": Path("data/gsd/corpus"),
                            "pairs": Path("data/gsd/pairs_gsd_corpus_not_unique.pkl"),
                            "trees": Path("data/gsd/tree_set_gsd_corpus.pkl"),
                            "ses": Path("data/gsd/ses_set_gsd_corpus.pkl"),
                            "ud_with_copy": Path("data/gsd/ud_with_copy_set_gsd_corpus.pkl"),
                            "ud_without_copy": Path("data/gsd/ud_without_copy_set_gsd_corpus.pkl"),
                            "dict_tree": Path("data/gsd/gsd_f_x_dict_tree.pkl"),
                            "dict_ses": Path("data/gsd/gsd_f_x_dict_ses.pkl"),
                            "dict_ud_with_copy": Path("data/gsd/gsd_f_x_dict_ud_with_copy.pkl"),
                            "dict_ud_without_copy": Path("data/gsd/gsd_f_x_dict_ud_without_copy.pkl")},
    'pud':                 {"corpus": Path("data/pud/corpus"),
                            "pairs": Path("data/pud/pairs_pud_corpus_not_unique.pkl"),
                            "trees": Path("data/pud/tree_set_pud_corpus.pkl"),
                            "ses": Path("data/pud/ses_set_pud_corpus.pkl"),
                            "ud_with_copy": Path("data/pud/ud_with_copy_set_pud_corpus.pkl"),
                            "ud_without_copy": Path("data/pud/ud_without_copy_set_pud_corpus.pkl"),
                            "dict_tree": Path("data/pud/pud_f_x_dict_tree.pkl"),
                            "dict_ses": Path("data/pud/pud_f_x_dict_ses.pkl"),
                            "dict_ud_with_copy": Path("data/pud/pud_f_x_dict_ud_with_copy.pkl"),
                            "dict_ud_without_copy": Path("data/pud/pud_f_x_dict_ud_without_copy.pkl")},
    'OpenCorpora':         {"corpus": Path("data/OpenCorpora/corpus"),
                            "pairs": Path("data/OpenCorpora/pairs_OpenCorpora_corpus_not_unique.pkl"),
                            "trees": Path("data/OpenCorpora/tree_set_OpenCorpora_corpus.pkl"),
                            "ses": Path("data/OpenCorpora/ses_set_OpenCorpora_corpus.pkl"),
                            "ud_with_copy": Path("data/OpenCorpora/ud_with_copy_set_OpenCorpora_corpus.pkl"),
                            "ud_without_copy": Path("data/OpenCorpora/ud_without_copy_set_OpenCorpora_corpus.pkl"),
                            "dict_tree": Path("data/OpenCorpora/OpenCorpora_f_x_dict_tree.pkl"),
                            "dict_ses": Path("data/OpenCorpora/OpenCorpora_f_x_dict_ses.pkl"),
                            "dict_ud_with_copy": Path("data/OpenCorpora/OpenCorpora_f_x_dict_ud_with_copy.pkl"),
                            "dict_ud_without_copy": Path("data/OpenCorpora/OpenCorpora_f_x_dict_ud_without_copy.pkl")},
    'SynTagRus_original':  {"corpus": None,
                            "pairs": Path("data/SynTagRus_original/pairs_SynTagRus_original_corpus_not_unique.pkl"),
                            "trees": Path("data/SynTagRus_original/tree_set_SynTagRus_original_corpus.pkl"),
                            "ses": Path("data/SynTagRus_original/ses_set_SynTagRus_original_corpus.pkl"),
                            "ud_with_copy": Path("data/SynTagRus_original/ud_with_copy_set_SynTagRus_original_corpus.pkl"),
                            "ud_without_copy": Path("data/SynTagRus_original/ud_without_copy_set_SynTagRus_original_corpus.pkl"),
                            "dict_tree": Path("data/SynTagRus_original/SynTagRus_original_f_x_dict_tree.pkl"),
                            "dict_ses": Path("data/SynTagRus_original/SynTagRus_original_f_x_dict_ses.pkl"),
                            "dict_ud_with_copy": Path("data/SynTagRus_original/SynTagRus_original_f_x_dict_ud_with_copy.pkl"),
                            "dict_ud_without_copy": Path("data/SynTagRus_original/SynTagRus_original_f_x_dict_ud_without_copy.pkl")},
    'RNC':                 {"corpus": None,
                            "pairs": Path("data/RNC/pairs_RNC_main_corpus_not_unique.pkl"),
                            "trees": Path("data/RNC/tree_set_RNC_main_corpus.pkl"),
                            "ses": Path("data/RNC/ses_set_RNC_main_corpus.pkl"),
                            "ud_with_copy": Path("data/RNC/ud_with_copy_set_RNC_main_corpus.pkl"),
                            "ud_without_copy": Path("data/RNC/ud_without_copy_set_RNC_main_corpus.pkl"),
                            "dict_tree": Path("data/RNC/RNC_main_f_x_dict_tree.pkl"),
                            "dict_ses": Path("data/RNC/RNC_main_f_x_dict_ses.pkl"),
                            "dict_ud_with_copy": Path("data/RNC/RNC_main_f_x_dict_ud_with_copy.pkl"),
                            "dict_ud_without_copy": Path("data/RNC/RNC_main_f_x_dict_ud_without_copy.pkl")}
}